version: "2"
services:
    easytax-app:
        build: .
        ports:
            - "1135:8080"
        links:
            - easytax
    easytax:
        image: mongo
        volumes:
            - ./data:/data/db