const CONDITION = 0;

module.exports = {
    forme_juridique_type: [
        { value: "SARL", type: "s", impot: [true, "Redevable Legale", "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, "Si vous vendez de la boisson", "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, "Si vous avez un permis forestier", "Si exploitant agréé", true, "Si vous êtes une société pétrolière distributrice agréée", "Si vous êtes une société distributrice de produits pétroliers raffinés agréée", "Si vous êtes un assureur", false, "Si vous avez des maisons en location", true, true, false] },
        { value: "SAS", type: "s",  impot: [true, "Redevable Legale", "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, "Si vous vendez de la boisson", "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, "Si vous avez un permis forestier", "Si exploitant agréé", true, "Si vous êtes une société pétrolière distributrice agréée", "Si vous êtes une société distributrice de produits pétroliers raffinés agréée", "Si vous êtes un assureur", false, "Si vous avez des maisons en location", true, true, false] },
        { value: "SUARL", type: "s",  impot: [true, "Redevable Legale", "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, "Si vous vendez de la boisson", "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, "Si vous avez un permis forestier", "Si exploitant agréé", true, "Si vous êtes une société pétrolière distributrice agréée", "Si vous êtes une société distributrice de produits pétroliers raffinés agréée", "Si vous êtes un assureur", false, "Si vous avez des maisons en location", true, true, false] },
        { value: "Société Anonyme", type: "s",  impot: [true, "Redevable Legale", "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, "Si vous vendez de la boisson", "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, "Si vous avez un permis forestier", "Si exploitant agréé", true, "Si vous êtes une société pétrolière distributrice agréée", "Si vous êtes une société distributrice de produits pétroliers raffinés agréée", "Si vous êtes un assureur", false, "Si vous avez des maisons en location", true, true, false]},
        { value: "Particulier", type: "p", impot: [false, true, "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", "Si vous êtes commercant", false, "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", "Si vous êtes employé", true, false, false, true, false, false, true, true, "Si vous avez des maisons en location", false, false, true] },
        { value: "Entreprise individuelle", type: "p", impot: [false, true, "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, false, "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, false, false, true, false, false, true, true, "Si vous avez des maisons en location", "Si vous êtes salarié", false, true] },
        { value: "Société coopératives", type: "s", impot: [true, false, "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, "Si vous vendez de la boisson", "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, "Si vous avez un permis forestier", "Si exploitant agréé", true, "Si vous êtes une société pétrolière distributrice agréée", "Si vous êtes une société distributrice de produits pétroliers raffinés agréée", "Si vous êtes un assureur", false, "Si vous avez des maisons en location", true, true, false] },
        { value: "Etablissement public", type: "s", impot: [] },
        { value: "Société en nom collectif", type: "s",impot: ["Si vous avez choisi l'IS en option", true, "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, "Si vous vendez de la boisson", "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, "Si vous avez un permis forestier", "Si exploitant agréé", true, "Si vous êtes une société pétrolière distributrice agréée", "Si vous êtes une société distributrice de produits pétroliers raffinés agréée", "Si vous êtes un assureur", false, "Si vous avez des maisons en location", true, true, false] },
        { value: "Société en commandite simple", type: "s", impot: ["Si vous avez choisi l'IS en option", true, "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, "Si vous vendez de la boisson", "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, "Si vous avez un permis forestier", "Si exploitant agréé", true, "Si vous êtes une société pétrolière distributrice agréée", "Si vous êtes une société distributrice de produits pétroliers raffinés agréée", "Si vous êtes un assureur", false, "Si vous avez des maisons en location", true, true, false]  },
        { value: "Société en participation", type: "s", impot: ["Si vous avez choisi l'IS en option", true, "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, "Si vous vendez de la boisson", "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, "Si vous avez un permis forestier", "Si exploitant agréé", true, "Si vous êtes une société pétrolière distributrice agréée", "Si vous êtes une société distributrice de produits pétroliers raffinés agréée", "Si vous êtes un assureur", false, "Si vous avez des maisons en location", true, true, false]  },
        { value: "Syndicat financiers", type: "s", impot: ["Si vous avez choisi l'IS en option", true, "Si votre chiffre d'affaire hors taxe est superieur ou égal à 150 millions", true, "Si vous vendez de la boisson", "Si vous avez un titre de propriété ou d'occupation", "Si vous avez un titre de propriété ou d'occupation", "Si le chiffre d'affaire hors taxe est superieur ou égale à 30 millions", true, true, "Si vous avez un permis forestier", "Si exploitant agréé", true, "Si vous êtes une société pétrolière distributrice agréée", "Si vous êtes une société distributrice de produits pétroliers raffinés agréée", "Si vous êtes un assureur", false, "Si vous avez des maisons en location", true, true, false]  },
        { value: "Organisme d’Etat autonome", type: "s", impot: [] },
        { value: "Syndicat agricole", type: "s", impot: [] },
        { value: "Caisse de crédit agricole mutuel", type: "s", impot: [] },
        { value: "Société et union de société de secours mutuel", type: "s", impot: [] },
        { value: "Association sans but lucratif", type: "s", impot: [false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, CONDITION, false, false,] },
        { value: "Collectivités locales", type: "s", impot: [] },
        { value: "Offices publics", type: "s", impot: [] },
        { value: "Mutuelles scolaires", type: "s", impot: [] },
        { value: "Clubs et cercles privés GIE", type: "s", impot: [] },
        { value: "Entreprises d’hôtellerie et de tourisme.", type: "s", impot: [] }
    ],

    getFormeJuridiqueArray: function () {
        const array = [];
        this.forme_juridique_type.forEach(ft => {
            array.push(ft.value);
        });
        return array;
    }
};